### ISSUE TITLE
```yaml

### ISSUE THREAD

**Issue by alexis1120** [alexis1120/Alexis#1]
```yaml
name: Memhash
description: ""
image": "https://storage.googleapis.com/memhash-general/meta/mh-logo.jpg"
address: EQDol2oVpmBznAL6vQpF51QW3p0PKV7ag4VEtex8_MeMHASH
symbol: MEMHASH
websites:
  - "https://memhash.org/"
social:
  - "https://t.me/memhash"
  - "https://x.com/memhash_app"
  ```

_Originally posted by @casper6479 in https://github.com/tonkeeper/ton-assets/pull/2485_
